version: "3.8"

services:
  http-server:
    build:
      context: ./server/http-server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  database:
    image: cassandra:latest
    ports:
      - "9042:9042"
